//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace RecoveryPasswordXAF.Module.BusinessObjects.Database
{

    public partial class ChangePassword : XPLiteObject
    {
        Guid fToken;
        [Key(true)]
        public Guid Token
        {
            get { return fToken; }
            set { SetPropertyValue<Guid>(nameof(Token), ref fToken, value); }
        }

        DateTime fDateRequest;

        [FetchOnly]
        public DateTime DateRequest
        {
            get { return fDateRequest; }
            set { SetPropertyValue<DateTime>(nameof(DateRequest), ref fDateRequest, value); }
        }
        string fUser;
        public string User
        {
            get { return fUser; }
            set { SetPropertyValue<string>(nameof(User), ref fUser, value); }
        }
    }

}
